### ISSUE TITLE
lispstring function to take a const char*

### ISSUE THREAD

**Issue by hasn0life** [technoblogy/ulisp-cardputer#1]
[This line specifically](https://github.com/technoblogy/ulisp-cardputer/blob/3fe6f50178f15d56549f7704d6ea99ed1606ccc8/ulisp-cardputer.ino#L1427). I think it makes sense since the buffer isn't modified, just copied. The ESP32 compiler complained about this when I tried to make a const string into a ulisp string, it seems to be more strict about it. I suspect you can make this change for all the ulisp variants but I have only tested it here.

**Comment by technoblogy** [comment]
Are you suggesting this change?

    object *lispstring (char *s) {

to:

    object *lispstring (const char *s) {

**Comment by hasn0life** [comment]
yes, I should have written that

**Comment by technoblogy** [comment]
I assume you're getting this warning with a statement such as:
````text
printobject(lispstring("Welcome to uLisp!"), pserial);

warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   printobject(lispstring("Welcome to uLisp!"), pserial);
````
Just do:

     printobject(lispstring((char*)"Welcome to uLisp!"), pserial);

**Comment by hasn0life** [comment]
Yes it can be fixed by casting, but don't you think that the conversion from a c string to a lisp one inherently shouldn't modify the underlying string, and therefore should take a const argument?

**Comment by technoblogy** [comment]
> don't you think that the conversion from a c string to a lisp one inherently shouldn't modify the underlying string

I don't quite understand. **lispstring()** doesn't modify its string argument.

But often it doesn't take a const string, such as where it is called from **internlong()**.

**Comment by hasn0life** [comment]
Maybe I'm wrong about this, but `object *lispstring (const char *s)` can take either const or non const strings while `object *lispstring (char *s)` can only take non const strings because it might modify them according to the function signature. When you type cast a const string to a non const one its mostly ok but if the function does try to modify the string the compiler might do weird stuff (undefined behavior) so you should tell the compiler you aren't going to modify it by making it const.

**Comment by technoblogy** [comment]
I'm reluctant to change it, because it doesn't seem to offer much benefit, and it will involve a lot of retesting on all the platforms. But I'll bear it in mind for the future.

Thanks! David

**Comment by hasn0life** [comment]
Thats understandable, in my experience changing a function to const doesn't cause problems if it compiles, but it is a broad reaching and subtle change so the potential for introducing bugs is there.
